name: Mirror

on:
  workflow_dispatch: {}

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - id: this
        env:
          VERBOSE: ${{ runner.debug }}
        run: |
          [ -n "${VERBOSE:-}" ] && set -x

          _G=''
          if uname -a | grep -i darwin; then
            _G='g'
          fi

          site="$(
            curl -sS -L -f https://download.openwall.net/pub/projects/passwdqc/  |
              grep -E '\.tar\.gz">passwdqc-' |
              while read -r line; do
                v="$(
                  echo "$line" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | sort -uV | head -n1
                )"
                t="$(
                  echo "$line" | awk '{print $7 " " $8}'
                )"
                printf '%s,%s\n' "$v" "$(${_G}date -d "$t" +'%Y-%m-%dT%H:%MZ')"
              done
          )"

          local="$(
            jq -r '.releases[]|.version' releases.json
          )"

          remote="$(echo "$site" | cut -d',' -f1)"

          diff="$(
            diff -u \
              <(echo "$local") \
              <(echo "$remote") || true
          )"

          echo "diff=${diff//$'\n'/'\n'}" >> $GITHUB_OUTPUT

      - if: steps.this.outputs.diff != ''
        env:
          VERBOSE: ${{ runner.debug }}
        run: |
          [ -n "${VERBOSE:-}" ] && set -x

          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - if: steps.this.outputs.diff != ''
        env:
          DIFF: ${{ steps.this.outputs.diff }}
          VERBOSE: ${{ runner.debug }}
        run: |
          [ -n "${VERBOSE:-}" ] && set -x

          for v in $(echo -e "$DIFF" | tail -n+3 | grep -E '^\+' | cut -d'+' -f2-); do
            wget -nv "https://download.openwall.net/pub/projects/passwdqc/passwdqc-${v}.tar.gz"

            t="$(echo "$site" | grep "$v" | cut -d',' -f2)"

            d="$(
              sha256sum ./passwdqc-${v}.tar.gz | cut -d' ' -f1
            )"

            jq --argjson _ "{
              \"version\": \"${v}\",
              \"digest\": \"${d}\",
              \"releaseTimestamp\": \"${t}\"
            }" '.releases += [$_]' releases.json > _releases.json
          done

          mv -v _releases.json releases.json
          git add releases.json
          git commit -m "chore(add): ${v}"
          git push origin gh-pages

      - id: deployment
        if: steps.this.outputs.diff != ''
        uses: actions/upload-pages-artifact@v3
        with:
          path: releases.json
